---
- name: Check Docker is installed
  ansible.builtin.command: which docker
  failed_when: false
  changed_when: false
  check_mode: false
  become: true
  register: _rpi_setup_docker_is_present

- name: Get get-docker.sh script
  ansible.builtin.get_url:
    url: https://get.docker.com/
    dest: /root/get-docker.sh
    mode: 0775
  become: true
  when: _rpi_setup_docker_is_present.rc == 1

- name: Run get-docker.sh script
  ansible.builtin.command: /root/get-docker.sh
  environment:
    CHANNEL: stable
  changed_when: _rpi_setup_docker_is_present.rc == 1
  become: true
  when: _rpi_setup_docker_is_present.rc == 1

- name: Manage Docker service
  ansible.builtin.systemd:
    name: docker.service
    state: started
    enabled: true
  become: true

- name: Manage Docker users
  ansible.builtin.user:
    name: "{{ docker_user }}"
    groups:
      - docker
    append: true
  loop: "{{ rpi_setup_docker_users }}"
  loop_control:
    loop_var: docker_user
  become: true

- name: Reset connection
  ansible.builtin.meta: reset_connection
