---
- name: Manage Docker Compose Service users
  ansible.builtin.user:
    name: "{{ service_user.name }}"
    password: "{{ service_user.password | password_hash('sha512') }}"
    uid: "{{ service_user.uid }}"
    gid: "{{ service_user.gid }}"
    groups: "{{ service_user.groups | d(omit) }}"
    shell: "{{ service_user.shell | d(omit) }}"
  loop: "{{ _rpi_setup_docker_service.users }}"
  loop_control:
    loop_var: service_user
  become: true

- name: Manage Docker Compose Service project folder
  ansible.builtin.file:
    path: "{{ _rpi_setup_docker_service.project_path }}"
    state: directory
    owner: root
    group: root
    mode: 0754
  become: true

- name: Manage Docker Secrets
  community.docker.docker_secret: "{{ docker_secret }}"
  loop: "{{ _rpi_setup_docker_service.docker_secrets | d([]) }}"
  loop_control:
    loop_var: docker_secret
  become: true
  no_log: "{{ rpi_setup_nolog_override | d(true) }}"

- name: Manage Docker Compose Service project file
  ansible.builtin.copy:
    dest: "{{ _rpi_setup_docker_service.project_path }}/docker-compose.yml"
    content: |
      ---
      {{ _rpi_setup_docker_service.configuration | to_nice_yaml(indent=2) }}
    owner: root
    group: root
    mode: 0644
  become: true

- name: Manage Docker Compose Service systemd unit
  ansible.builtin.template:
    src: docker-service.service.j2
    dest: "/etc/systemd/system/docker-{{ _rpi_setup_docker_service.name }}.service"
    owner: root
    group: root
    mode: 0644
  become: true

- name: Manage Docker Compose Service systemd service
  ansible.builtin.systemd:
    name: "{{ _rpi_setup_docker_service.name }}"
    state: "{{ _rpi_setup_docker_service.state | d(omit) }}"
    enabled: "{{ _rpi_setup_docker_service.enabled | bool }}"
    daemon_reload: true
  become: true
