---
- name: Manage Docker Compose Service users
  ansible.builtin.user:
    name: "{{ service_user.name }}"
    password: "{{ service_user.password | password_hash('sha512') }}"
    uid: "{{ service_user.uid }}"
    gid: "{{ service_user.gid }}"
    groups: "{{ service_user.groups | d(omit) }}"
    shell: "{{ service_user.shell | d(omit) }}"
  loop: "{{ _rpi_setup_docker_service.users | d(false, true) }}"
  loop_control:
    loop_var: service_user
  become: true

- name: Manage Docker Compose Service project folder
  ansible.builtin.file:
    path: "{{ _rpi_setup_docker_service.project_path }}"
    state: directory
    owner: root
    group: root
    mode: 0754
  become: true

- name: Manage Docker Secrets (external)
  community.docker.docker_secret: "{{ docker_secret_external.configuration }}"
  loop: "{{ _rpi_setup_docker_service.docker_secrets | selectattr('type', 'external') }}"
  loop_control:
    loop_var: docker_secret_external
  become: true
  when: _rpi_setup_docker_service.docker_secrets | d([], true) | selectattr('type', 'external') | length
  no_log: "{{ rpi_setup_nolog_override | d(true) }}"

- name: Manage Docker Compose Service secrets folder
  ansible.builtin.file:
    path: "{{ _rpi_setup_docker_service.project_path }}/secrets"
    state: directory
    owner: root
    group: root
    mode: 0754
  become: true
  when: _rpi_setup_docker_service.docker_secrets | d([], true) | selectattr('type', 'file') | length
  no_log: "{{ rpi_setup_nolog_override | d(true) }}"

- name: Manage Docker Secrets (file)
  ansible.builtin.copy:
    dest: "{{ _rpi_setup_docker_service.project_path }}/secrets/{{ docker_secret_file.filename }}"
    content: |
      {{ docker_secret_file.content }}
    create: true
    owner: root
    group: root
    mode: 0644
  loop: "{{ _rpi_setup_docker_service.docker_secrets | selectattr('type', 'file') }}"
  loop_control:
    loop_var: docker_secret_file
  become: true
  when: _rpi_setup_docker_service.docker_secrets | d([], true) | selectattr('type', 'file') | length
  no_log: "{{ rpi_setup_nolog_override | d(true) }}"

- name: Manage Docker Compose Service env file
  ansible.builtin.copy:
    dest: "{{ _rpi_setup_docker_service.project_path }}/.env"
    content: |
      {{ _rpi_setup_docker_service.docker_env }}
    create: true
    owner: root
    group: root
    mode: 0644
  become: true
  when: _rpi_setup_docker_service.docker_env | d(false, true)

- name: Manage Docker Compose Service project file
  ansible.builtin.copy:
    dest: "{{ _rpi_setup_docker_service.project_path }}/docker-compose.yml"
    content: |
      ---
      {{ _rpi_setup_docker_service.configuration | to_nice_yaml(indent=2) }}
    create: true
    owner: root
    group: root
    mode: 0644
  become: true

- name: Manage Docker Compose Service systemd unit
  ansible.builtin.template:
    src: docker-service.service.j2
    dest: "/etc/systemd/system/docker-{{ _rpi_setup_docker_service.name }}.service"
    owner: root
    group: root
    mode: 0644
  become: true

- name: Manage Docker Compose Service systemd service
  ansible.builtin.systemd:
    name: "{{ _rpi_setup_docker_service.name }}"
    state: "{{ _rpi_setup_docker_service.state | d(omit) }}"
    enabled: "{{ _rpi_setup_docker_service.enabled | bool }}"
    daemon_reload: true
  become: true
