---
- name: Gather facts
  ansible.builtin.setup:
    gather_subset:
      - "min"
      - "!facter"
  become: true
  when: ansible_fqdn is not defined

- name: Manage base Raspberry Pi setup
  ansible.builtin.include_tasks: base.yml
  when: ('base' in rpi_setup_configure_resources)

- name: Manage Raspberry Pi configurations
  ansible.builtin.include_tasks: rpi.yml
  when: ('rpi' in rpi_setup_configure_resources)

- name: Reboot Raspberry Pi if required
  ansible.builtin.include_tasks: reboot.yml
  when: _rpi_setup_reboot_required

- name: Manage rpwcs
  ansible.builtin.include_tasks: rpwcs.yml
  when: ('rpwcs' in rpi_setup_configure_resources)

- name: Manage vsftpd
  ansible.builtin.include_tasks: vsftpd.yml
  when: ('vsftpd' in rpi_setup_configure_resources)

- name: Manage Raspberry Pi Docker
  ansible.builtin.include_tasks: docker.yml
  when: ('docker' in rpi_setup_configure_resources)

- name: Manage Raspberry Pi Docker Compose Services
  ansible.builtin.include_tasks: docker_service.yml
  loop: "{{ rpi_setup_docker_services }}"
  loop_control:
    loop_var: _rpi_setup_docker_service
  when: ('docker_services' in rpi_setup_configure_resources)
