---
- name: Gather info
  ansible.builtin.include_tasks: _gather_info.yml

- name: Check architecture and OS version are supported
  ansible.builtin.assert:
    that:
      - ansible_architecture in ('armhf', 'aarch64')
      - ansible_distribution == 'Debian'
      - ansible_distribution_major_version >= 11
    msg: "This role requires Debian 11 or newer on ARM x86/64"

- name: Manage Raspberry Pi APT
  ansible.builtin.include_tasks: apt.yml
  when: ('apt' in rpi_setup_configure_resources)

- name: Manage Raspberry Pi main user
  ansible.builtin.include_tasks: user.yml
  when: ('user' in rpi_setup_configure_resources)

- name: Manage Raspberry Pi boot configurations
  ansible.builtin.include_tasks: boot.yml
  when: ('boot' in rpi_setup_configure_resources)

- name: Manage Raspberry Pi locale configurations
  ansible.builtin.include_tasks: locale.yml
  when: ('locale' in rpi_setup_configure_resources)

- name: Manage Raspberry Pi time configurations
  ansible.builtin.include_tasks: time.yml
  when: ('time' in rpi_setup_configure_resources)

- name: Manage Raspberry Pi network configurations
  ansible.builtin.include_tasks: network.yml
  when: ('network' in rpi_setup_configure_resources)

- name: Manage Raspberry Pi mounts
  ansible.builtin.include_tasks: mounts.yml
  when: ('mounts' in rpi_setup_configure_resources)

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Reboot Raspberry Pi if required
  ansible.builtin.include_tasks: reboot.yml
  when: _rpi_setup_reboot_required

- name: Manage Raspberry Pi Web Control Server
  ansible.builtin.include_tasks: rpwcs.yml
  when: ('rpwcs' in rpi_setup_configure_resources)

- name: Manage Raspberry Pi FTP server
  ansible.builtin.include_tasks: vsftpd.yml
  when: ('vsftpd' in rpi_setup_configure_resources)

- name: Manage Raspberry Pi Docker
  ansible.builtin.include_tasks: docker.yml
  when: ('docker' in rpi_setup_configure_resources)

- name: Manage Raspberry Pi Docker Compose Services
  ansible.builtin.include_tasks: docker_service.yml
  loop: "{{ rpi_setup_docker_services }}"
  loop_control:
    loop_var: _rpi_setup_docker_service
  when: ('docker_services' in rpi_setup_configure_resources)
