---
- name: Manage hostname
  ansible.builtin.hostname:
    name: "{{ rpi_setup_network_hostname }}"
    use: systemd
  notify: rpi_setup_gather_info_handler

- name: Manage /etc/hosts
  ansible.builtin.template:
    src: etc_hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
    unsafe_writes: true
  become: true

- name: Manage /etc/resolv.conf
  ansible.builtin.template:
    src: etc_resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  become: true

- name: Manage dhcpcd.conf main interface static options
  ansible.builtin.blockinfile:
    dest: /etc/dhcpcd.conf
    block: |
      interface {{ rpi_setup_config_dhcpcd_interface }}
      static ip_address={{ rpi_setup_config_dhcpcd_ip }}
      static routers={{ rpi_setup_config_dhcpcd_gateway }}
      static domain_name_servers={{ rpi_setup_config_dhcpcd_dns_servers | join(' ') }}
  become: true
  notify: rpi_setup_reboot_required_handler
