---
- name: Reset reboot flag
  ansible.builtin.set_fact:
    _rpi_setup_reboot_required: false

- name: Reboot Raspberry Pi
  ansible.builtin.reboot:

- name: Force info update
  ansible.builtin.include_tasks: _gather_info.yml
