---
- name: Create Raspberry Pi Web Control Server folder
  ansible.builtin.file:
    path: "{{ _rpi_setup_rpwcs_install_path }}"
    state: directory
    owner: root
    group: root
    mode: 0644
  become: true

- name: Install Raspberry Pi Web Control Server files
  ansible.builtin.copy:
    src: rpwcs
    dest: "{{ _rpi_setup_rpwcs_install_path }}"
    owner: root
    group: root
    mode: 0644
    directory_mode: 0754
  become: true

- name: Manage Raspberry Pi Web Control Server python virtualenv
  ansible.builtin.pip:
    name: "{{ _rpi_setup_python_modules_default + _rpi_setup_rpwcs_python_modules }}"
    virtualenv: "{{ _rpi_setup_rpwcs_venv_path }}"
    virtualenv_command: "{{ rpi_setup_python_command }} -m venv"
  become: true

- name: Manage Raspberry Pi Web Control Server service file
  ansible.builtin.template:
    src: rpwcs.service.j2
    dest: /etc/systemd/system/rpwcs.service
    owner: root
    group: root
    mode: 0644
  become: true

- name: Manage Raspberry Pi Web Control Server status
  ansible.builtin.systemd:
    name: rpwcs.service
    state: "{{ rpi_setup_rpwcs_service_state }}"
    enabled: "{{ rpi_setup_rpwcs_service_enabled | bool }}"
    daemon_reload: true
  become: true
