---
- name: Remove NTP
  ansible.builtin.apt:
    name: ntp
    state: absent
    purge: true
    autoclean: true
    autoremove: true
  become: true
  notify: rpi_setup_gather_info_handler

- name: Manage systemd-timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd.service
    state: started
    enabled: true
    daemon_reload: true
  become: true
  notify: rpi_setup_gather_info_handler

- name: Manage timezone
  community.general.timezone:
    name: "{{ rpi_setup_time_zone }}"
  notify: rpi_setup_gather_info_handler
