---
- name: Restart vsftpd
  ansible.builtin.systemd:
    name: vsftpd
    state: restarted
  become: true
  when: rpi_setup_vsftpd_service_state != 'stopped'
  listen: rpi_setup_vsftpd_service_restart_handler

- name: Restart dhcpcd
  ansible.builtin.systemd:
    name: dhcpcd
    state: restarted
  become: true
  listen: rpi_setup_dhcpcd_service_restart_handler

- name: Raspberry Pi reboot is required
  ansible.builtin.set_fact:
    _rpi_setup_reboot_required: true
  listen: rpi_setup_reboot_required_handler
