---
- name: Gather info
  ansible.builtin.include_tasks: _gather_info.yml
  listen: rpi_setup_gather_info_handler

- name: Restart vsftpd
  ansible.builtin.systemd:
    name: vsftpd.service
    state: restarted
  become: true
  when: rpi_setup_vsftpd_service_state != 'stopped'
  listen: rpi_setup_vsftpd_service_restart_handler

- name: Raspberry Pi reboot is required
  ansible.builtin.set_fact:
    _rpi_setup_reboot_required: true
  listen: rpi_setup_reboot_required_handler
